### PR TITLE
Claude chat completions

### PR DESCRIPTION
**Pull request by ejfox**

### CODE REVIEW

**Comment by ejfox** [comment]
Two errors right now when using Claude as the chat completion for Discord messages:

```
2024-03-15T05:34:20.629Z helpers  : Error creating chat completion TypeError: Assignment to constant variable.
2024-03-15T05:34:20.630Z chain  : Process message chain: error processing message: TypeError: Cannot read properties of null (reading 'data')
```

**Comment by ejfox** [comment]
```
2024-03-18T01:39:58.706Z helpers  : Error creating chat completion Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: Unexpected role \"system\". The Messages API accepts a top-level `system` parameter, not \"system\" as an input message role."}}
```

**Comment by ejfox** [comment]
TODO before merge:
- [ ] Use config from supabase to determine which model to use for completion

**Comment by curran** [comment]
Oh wow this is huge!

**Comment by ejfox** [comment]
First attempt at formatting the messages to XML as a single user message for Claude


https://gist.github.com/ejfox/64b2f280ce204f6da9f20dd56e72a564

**Pull request merged**
