### PR TITLE
feat: prompts in supabase

### PR DESCRIPTION
**Pull request by ejfox**
### Prompts Table
```sql
create table
  public.prompts (
    id integer generated by default as identity,
    prompt_name text null,
    prompt_text text null,
    notes text null,
    type text null,
    active boolean null,
    updated_at timestamp with time zone not null default now(),
    archived boolean null default false,
    history jsonb null default '[]'::jsonb,
    created_at timestamp with time zone not null default now(),
    constraint prompts_pkey primary key (id)
  ) tablespace pg_default;
```

### Config Table
```sql
create table
  public.config (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    config_key text not null unique,
    config_value text not null,
    history jsonb not null default '[]'::jsonb,
    constraint config_pkey primary key (id)
  ) tablespace pg_default;
```

### CODE REVIEW

**Comment by ejfox** [comment]
Tachio prompts table

[prompts_rows.csv](https://github.com/room302studio/coachartie/files/14607334/prompts_rows.csv)

**Comment by ejfox** [comment]
Need to test this on the Missive endpoints before merging

**Comment by ejfox** [comment]
Working in Missive

**Comment by rajivsinclair** [comment]
### Re: automatically retaining history in Postgres

The `history` columns will only autopopulate iff you also setup matching Postgres triggers+functions for each table. Here's [a step-by-step guide](https://chat.openai.com/share/595c8112-8dfe-4afb-b4c4-f26e497a7b37).

> _Create a trigger function that captures changes, including the original creation of a row. The function will append a new entry to the history column, containing the old values of the record, the datetime when the change was made, and the datetime range the version was in effect._


```sql
CREATE OR REPLACE FUNCTION public.fn_record_prompt_history()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        NEW.history := jsonb_insert(NEW.history, '{0}', jsonb_build_object(
            'version', OLD,
            'valid_from', COALESCE(OLD.valid_to, OLD.created_at),
            'valid_to', NOW()
        ));
    ELSIF TG_OP = 'INSERT' THEN
        NEW.history := jsonb_build_array(jsonb_build_object(
            'version', NEW,
            'valid_from', NEW.created_at,
            'valid_to', NULL
        ));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
```

This function does the following:
- For updates (`TG_OP = 'UPDATE'`), it prepends the history with the old version of the row, including when this version became valid and when it was replaced.
- For inserts (`TG_OP = 'INSERT'`), it initializes the history with the current version of the row, marking when it was created. The `valid_to` is set to `NULL` as it's the current version.

Note: This assumes you have `created_at` and optionally `valid_to` fields in your table to track when records are created and updated. If you don't have these fields, you'll need to add them or adjust the logic accordingly.


Next, create a trigger to invoke the function for both INSERT and UPDATE operations.


```sql
CREATE TRIGGER trg_record_prompt_history
BEFORE INSERT OR UPDATE ON public.prompts
FOR EACH ROW
EXECUTE FUNCTION public.fn_record_prompt_history();
```

This trigger ensures that every time a row in the "prompts" table is inserted or updated, the `fn_record_prompt_history()` function is called to update the history accordingly.

**Pull request merged**
